### ISSUE TITLE
Where do I set the USERPROFILE environment variable

### ISSUE THREAD

**Issue by cw123hb** [nrdrch/keyhelper#1]
I get this message when running the app: `Failed to fetch USERPROFILE environment variable.`

**Comment by nrdrch** [comment]
You don't have to set that variable.
I'm assuming you're using Linux and I'll add support for it in the next 24 hours!
I was planning on doing that and left my documentation lacking.

**Comment by cw123hb** [comment]
Thx. I am using Linux. It now works.
